# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'uikit-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for uikit-test
  pod 'SnapKit', '~> 5.6.0'
  pod 'Toast-Swift', '~> 5.0.1'

  target 'uikit-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'uikit-testUITests' do
    # Pods for testing
  end

end
